name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: move to solution directory
      run: cd my-app-api
    - name: Display current directory and move to solution folder
      run: pwd | ls
    - name: Restore dependencies
      run: dotnet restore my-app-api/
    - name: Build
      run: dotnet build my-app-api/ --no-restore
    - name: Test
      run: dotnet test my-app-api/ --no-build --verbosity normal
